name: Build and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.host }}
    strategy:
      matrix:
        host: [x86_64-linux]
        target: [x86_64-linux, aarch64-linux, x86_64-windows]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Build
        run: zig build ${{ matrix.host != matrix.target && format('-Dtarget={0}', matrix.target) || '' }} --summary all

      - name: Test
        if: ${{ matrix.host == matrix.target }}
        run: zig build test
