name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: x86_64-linux
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Build for all targets and run tests
        run: zig build ci --summary new
